# Generated by Django 5.1.2 on 2024-11-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_id', models.CharField(max_length=60)),
                ('Nombre', models.CharField(max_length=60)),
                ('Direccion', models.CharField(max_length=60)),
                ('Ciudad', models.CharField(max_length=60)),
                ('Telefono', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='distri_prod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Distribu_ID', models.CharField(max_length=60)),
                ('NombreD', models.CharField(max_length=60)),
                ('Tipo_distribu', models.CharField(max_length=60)),
                ('Ubicacion', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Domiciliario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Domiciliario_ID', models.CharField(max_length=60)),
                ('Nombre_dom', models.CharField(max_length=60)),
                ('Telefono_Dom', models.CharField(max_length=60)),
                ('Disponible', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Metodo_de_Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Met_pago_ID', models.CharField(max_length=60)),
                ('Precio_ped', models.CharField(max_length=60)),
                ('Modo_de_Pago', models.CharField(max_length=60)),
                ('Estado_de_Pago', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido_id', models.CharField(max_length=60)),
                ('ID_cliente', models.CharField(max_length=60)),
                ('ID_producto', models.CharField(max_length=60)),
                ('ID_met_pago', models.CharField(max_length=60)),
                ('ID_domiciliario', models.CharField(max_length=60)),
                ('Fecha_de_Pedido', models.CharField(max_length=60)),
                ('Precio_de_Pedido', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto_ID', models.CharField(max_length=60)),
                ('Nombre_pro', models.CharField(max_length=60)),
                ('Cantidad_pro', models.CharField(max_length=60)),
                ('Precio_pro', models.CharField(max_length=60)),
                ('ID_distribu', models.CharField(max_length=60)),
            ],
        ),
    ]
